// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzDtZdkilKTK-mqZveUTL4GtjpG-E0YhQ',
    appId: '1:356015528105:web:93906c609edbc2988b71b8',
    messagingSenderId: '356015528105',
    projectId: 'fraseando-34cd3',
    authDomain: 'fraseando-34cd3.firebaseapp.com',
    storageBucket: 'fraseando-34cd3.appspot.com',
    measurementId: 'G-7QM8CXD7DP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN3MPrzxSu4ivRbjyoxhZUJ918vLxyOj8',
    appId: '1:356015528105:android:712615cb517aad2a8b71b8',
    messagingSenderId: '356015528105',
    projectId: 'fraseando-34cd3',
    storageBucket: 'fraseando-34cd3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVjlQjij0Ta8h29Oa2TZtTynOWz7T4xsw',
    appId: '1:356015528105:ios:d0e33073edcc07378b71b8',
    messagingSenderId: '356015528105',
    projectId: 'fraseando-34cd3',
    storageBucket: 'fraseando-34cd3.appspot.com',
    iosClientId: '356015528105-ptsr3l4qagannh2pngmmaf9hha1ukoto.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVjlQjij0Ta8h29Oa2TZtTynOWz7T4xsw',
    appId: '1:356015528105:ios:d0e33073edcc07378b71b8',
    messagingSenderId: '356015528105',
    projectId: 'fraseando-34cd3',
    storageBucket: 'fraseando-34cd3.appspot.com',
    iosClientId: '356015528105-ptsr3l4qagannh2pngmmaf9hha1ukoto.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzDtZdkilKTK-mqZveUTL4GtjpG-E0YhQ',
    appId: '1:356015528105:web:7253ecf9197155e88b71b8',
    messagingSenderId: '356015528105',
    projectId: 'fraseando-34cd3',
    authDomain: 'fraseando-34cd3.firebaseapp.com',
    storageBucket: 'fraseando-34cd3.appspot.com',
    measurementId: 'G-GLZX7QCDSJ',
  );

}